### ISSUE TITLE
Build and Publish failing

### ISSUE THREAD

**Issue by olopsman** [dxatscale/dxatscale-template#30]
Playing around with this and running it for the first time. I get an error on the Build and Phase stage - 

 Permission installation not allowed to Create organization package

`Publishing core
  Publishing core Version 1.0.0-4571028596 with tag main...
  npm notice 
  npm notice package: @olopsman/core_sfpowerscripts_artifact@1.0.0-4571028596
  npm notice === Tarball Contents === 
  npm notice 1.2kB artifact_metadata.json                                                                 
  npm notice 276B  changelog.json                                                                         
  npm notice 150B  package.json                                                                           
  npm notice 670B  source/.forceignore                                                                    
  npm notice 801B  source/config/project-scratch-def.json                                                 
  npm notice 684B  source/forceignores/.buildignore                                                       
  npm notice 684B  source/forceignores/.prepareignore                                                     
  npm notice 684B  source/forceignores/.quickbuildignore                                                  
  npm notice 684B  source/forceignores/.validateignore                                                    
  npm notice 2.1kB source/manifests/sfdx-project.json.ori                                                 
  npm notice 267B  source/sfdx-project.json                                                               
  npm notice 481B  source/src/core-crm/main/default/objects/Account/fields/AccountNumber__c.field-meta.xml
  npm notice 88B   source/src/core-crm/README.md                                                          
  npm notice === Tarball Details === 
  npm notice name:          @olopsman/core_sfpowerscripts_artifact                     
  npm notice version:       1.0.0-4571028596                                           
  npm notice filename:      @olopsman/core_sfpowerscripts_artifact-1.0.0-4571028596.tgz
  npm notice package size:  2.3 kB                                                     
  npm notice unpacked size: 8.8 kB                                                     
  npm notice shasum:        e44[19](https://github.com/olopsman/sfdxscale/actions/runs/4571028596/jobs/8069005370#step:8:20)0d28ffb590d58964ee0674[20](https://github.com/olopsman/sfdxscale/actions/runs/4571028596/jobs/8069005370#step:8:21)cc9a1507e1b                   
  npm notice integrity:     sha512-5KGZuvAd6Zbq5[...]/6NpZLDsDsW9Q==                   
  npm notice total files:   13                                                         
  npm notice 
  npm notice Publishing to https://npm.pkg.github.com/
  npm ERR! code E403
  npm ERR! 403 403 Forbidden - PUT https://npm.pkg.github.com/@olopsman%2fcore_sfpowerscripts_artifact - Permission installation not allowed to Create organization package
  npm ERR! 403 In most cases, you or one of your dependencies are requesting
  npm ERR! 403 a package version that is forbidden by your security policy, or
  npm ERR! 403 on a server you do not have access to.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /github/home/.npm/_logs/20[23](https://github.com/olopsman/sfdxscale/actions/runs/4571028596/jobs/8069005370#step:8:24)-03-31T02_50_[25](https://github.com/olopsman/sfdxscale/actions/runs/4571028596/jobs/8069005370#step:8:26)_[40](https://github.com/olopsman/sfdxscale/actions/runs/4571028596/jobs/8069005370#step:8:41)9Z-debug-0.log`

**Comment by azlam-abdulsalam** [comment]
@olopsman Can you check this  doc and see whether you are missing anything?

https://docs.dxatscale.io/implementing-your-ci-cd/github-1/getting-started

**Comment by olopsman** [comment]
Hey, @azlam-abdulsalam I've been actually following that guide and could use an update. I managed to fix it by going to the repository Settings > Actions > General and updating workflow permissions to read and write permissions. I'll close this comment.

**Comment by azlam-abdulsalam** [comment]
Thanks @olopsman
